languages = {
    "pt": {
              "string_other_language": "See in English", 
                     "string_contact": "Contato", 
                      "string_skills": "Conhecimentos", 
                   "string_languages": "Idiomas", 
                "string_languages_pt": "Português (Nativo)", 
                "string_languages_en": "Inglês", 
                "string_languages_es": "Espanhol", 
                "string_languages_ja": "Japonês", 
                        "string_read": "Leitura", 
                       "string_write": "Escrita", 
                       "string_speak": "Fala", 
                       "string_about": "Sobre Mim", 
              "string_about_contents": "<p class=\"text-justify\">Curioso desde novo sobre como os jogos no video-game, os programas no computador e mais tarde os websites funcionavam, eu sempre me senti atraído pela tecnologia e seu mistério e também em como ela podia facilitar as coisas para mim. Com o passar do tempo a curiosidade só aumentou quando eu olhava o código-fonte dos sites para descobrir como eles conseguiam fazer tantas coisas que pra mim eram incríveis e eu também queria saber como fazê-las. Uma coisa leva a outra e a internet era a melhor biblioteca e sala de estudos que alguém poderia ter.</p><p class=\"text-justify m-0\">Decidido a querer levar essa paixão como profissão, me especializei e trabalhei em lugares onde meus conhecimentos eram testados e sempre estava em contato com novas tecnologias. Curioso e interessado em estar sempre a par do mais moderno em relação ao desenvolvimento, estou sempre procurando e estudando as novidades da área e me sinto extremamente à vontade em ambientes em constante mudança e multidisciplinares.</p>", 
                  "string_employment": "Histórico Profissional", 
           "string_job_description_1": "Durante o estágio na Bowne, uma empresa de relações com investidores, minhas atribuições eram fazer manutenção e implementar os designs dos websites das empresas-clientes. Na maior parte atuando no front-end com HTML, CSS e JavaScript/jQuery, mas esporadicamente alterando ou corrigindo templates em ASP.", 
           "string_job_description_2": "Como parte do time de colaboradaores de TI, atuava no desenvolvimento do portal de colaboração científica onde os astrônomos trabalhavam. Atuando junto com cientistas e desenvolvedores em outros estados tanto no back-end utilizando Python quanto no front-end com HTML, CSS e JavaScript/jQuery.", 
           "string_job_description_3": "Atuei no desenvolvimento de sistemas ERP utilizados através do navegador para várias empresas cuidando da criação e manutenção tanto do front- quanto do back-end. Participava também das tomadas de decisão sobre a infraestrutura e tecnologias que seriam utilizadas para atender cada cliente.",
           "string_job_description_4": "Como colaborador externo desenvolvi uma aplicação em Python utilizando Tkinter para que os tradutores pudessem fazer as marcações em vídeos com os tempos das traduções, gerando arquivos que os dubladores posteriormente utilizam em estúdio para dublar o material original.", 
           "string_job_description_5": "Como desenvolvedor web, atuo na implementação de vários projetos para diferentes clientes de diversas áreas de atuação em uma fábrica de software tanto no front- quanto no back-end utilizando diversas tecnologias como Python com Django ou JavaScript com React.", 
                   "string_education": "Educação", 
                      "string_finish": "Conclusão em", 
                    "string_finished": "Concluído em", 
                 "string_interrupted": "Interrompido", 
                    "string_postgrad": "Pós-graduação", 
                        "string_grad": "Graduação", 
                    "string_course_1": "Ciências da Computação", 
                    "string_course_2": "Sistemas Para Internet", 
                    "string_course_3": "Desenvolvimento em Tecnologias Digitais", 
            "string_python_developer": "Desenvolvedor Python", 
               "string_web_developer": "Desenvolvedor web", 
        "string_web_developer_intern": "Desenvolvedor web estagiário", 
                     "string_current": "atual", 
    }, 
    "en": {
              "string_other_language": "Ver em português", 
                     "string_contact": "Contact", 
                      "string_skills": "Skills", 
                   "string_languages": "Languages", 
                "string_languages_pt": "Portuguese (Native)", 
                "string_languages_en": "English", 
                "string_languages_es": "Spanish", 
                "string_languages_ja": "Japanese", 
                        "string_read": "Reading", 
                       "string_write": "Writing", 
                       "string_speak": "Speaking", 
                       "string_about": "About Me", 
              "string_about_contents": "<p class=\"text-justify\">Curious since a young age about how the video-games, the computer programs, and later websites worked, I always felt attracted to technology and its mystery and also how it could make things easier for me. As time went by the curiosity only grew when I looked into the source code of websites to discover how they could do so many things that for me were amazing and I wanted to know how to do them too. One thing leads to another and the internet was the best library and study room that anyone could have.</p><p class=\"text-justify m-0\">Decided to take this passion ahead as a profession, I specialized in it and worked at places where my knowledge was tested and I always were in contact with new technologies. Curious and interested in being always up to par with what was being used for development, I am always looking into new technologies and studying about them and feel extremely at home in ever-changing and multidisciplinary environments.</p>", 
                  "string_employment": "Employment History", 
           "string_job_description_1": "During the internship at Bowne, an investors relations company, my attributions were to maintain and implement the designs of the websites of client-companies. Most of the time acting on the front-end with HTML, CSS and JavaScript/jQuery, but sporadically altering or correcting templates in ASP.", 
           "string_job_description_2": "As part of the team of IT collaborators, I developed the scientific collaboration portal where the astronomers worked. Acting alongside scientists and developers in other states both on front-end development using Python and front-end development using HTML, CSS and JavaScript/jQuery.", 
           "string_job_description_3": "I was part in the development of ERP systems used through the web browser for various companies taking part on the creation and maintenance of both the front- and back-end. I also participated on decision-taking about infrastructure and technologies that were to be used to answer to every client's need.",
           "string_job_description_4": "As an external collaborator I developed an application in Python using Tkinter so that the translators could mark videos with the timecodes of the translations, generating files that voice actors would later use in studio to dub the original material.", 
           "string_job_description_5": "As a web developer, I work implementing various projects for different clients of diverse acting areas at a software factory on front- as well as back-end utilizing several technologies like Python with Django or JavaScript with React.", 
                   "string_education": "Education", 
                      "string_finish": "Finish on", 
                    "string_finished": "Finished on", 
                 "string_interrupted": "Interrupted", 
                    "string_postgrad": "Postgrad", 
                        "string_grad": "Degree", 
                    "string_course_1": "Computer Sciences", 
                    "string_course_2": "Internet Systems", 
                    "string_course_3": "Development in Digital Technologies", 
            "string_python_developer": "Python developer", 
               "string_web_developer": "Web developer", 
        "string_web_developer_intern": "Web developer intern", 
                     "string_current": "current", 
    }
}
